### ISSUE TITLE
Automate rubix-edge-wires migration

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/module-migration#4]
### Summary

There are a couple of manual operations for `rubix-edge-wires` migrations where `rubix-ce` needs to be there to format the raw `JSON`. Let's step down those operations, so I could able to do these operations in bulk.

### Tasks to do

- [ ] Parse `/data/rubix-edge-wires/data/data.db` in a JSON object -- currently I am fetching it from API
- [ ] Apply that module name replacement logic -- we already have it
- [ ] See rubix-ce parser for converting that JSON and try to create `/data/rubix-edge-wires/data/data.json`
